site_name: MKDocs youTube Tutorial
theme:
name: material
features:
- navigation.tabs
- navigation.sections
- toc.integrate
- navigation.top
- search.suggest
- search.gighlight
- content.tabs.link
- content.code.annotation
- content.code.copy
language:en
palette:
- scheme: default
toggle:
icon: material/toggle-switch-off-outline
name: switch to dark mode
primary: teal
accent: purple
- scheme: slate
toggle: 
icon: material/toggle-switch
name: switch to light mode
primary: teal
accent: lime
extra:
social:
- icon: fontwesome/brands/githup-alt
- icon: fontwesome/brands/twitter
- icon: fontwesome/brands/linkedin
markdown_extensions
- pymdownx.inlinehilite:
 - pymdownx.snippets
 - admonition
 - pymdownx.arithmatex:
 generic: true
 - footnotes
 - pymdownx.suberfences
 -pymdownx.mark
 - attr_list
 - pymdownx.emoji:
emoji_index: !!python/name:materialx.emoji.twemoji
emoji_generator: !!python/name:materialx.emoji.to_svg

 
   

copyright:
@coby; 2023
